### PR TITLE
Drop Ruby 2.4/2.5/2.6 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by alexjfisher** [comment]
Echoing https://github.com/voxpupuli/puppet-blacksmith/pull/109#issuecomment-1474171820 I'd only drop 2.4 for now as I don't think you're helping anyone by being overly aggressive without tangible benefits.

Puppet 6 (with Ruby 2.5) has only _just_ gone EOL.  IMO it's not helping people upgrading from 6 to 7 if we drop ruby 2.5 support in all the core testing gems.

**Comment by alexjfisher** [comment]
Will this limit its inclusion with the PDK?

**Comment by bastelfreak** [comment]
I don't think so. Why should it limit this? pdk-tempaltes just needs to pin to the current major version of rspec-puppet-facts. Which it already does: https://github.com/puppetlabs/pdk-templates/blob/2.7.3/config_defaults.yml#L587-L588

**Comment by alexjfisher** [comment]
But it will then miss out on the legacy facts stuff we've started working on, and I think that would be a shame and hurt users.

**Comment by bastelfreak** [comment]
We don't need to merge this now, we can first merge https://github.com/voxpupuli/rspec-puppet-facts/pull/143 and do a final minor release.

**Comment by alexjfisher** [comment]
Until supporting ruby 2.5 is actually holding us back (limiting what version of rubocop we can use, or some new ruby feature we would like), I'm strongly in favour of not advancing past the versions of ruby that ship with the PDK.

**Comment by ekohl** [comment]
I agree with @alexjfisher that - besides beaker - dropping Ruby 2.5 is a tad too aggressive for now.

**Review by ekohl — APPROVED** [review]
@alexjfisher I'm not sure that compatibility limitation really relevant here, unless you intend to really run the test suite with Ruby 2.6.

In #150 we can see that Ruby 2.5 is holding us back so I'm ok with raising it to 2.7.

**Pull request merged**
